# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

traefik:
  repository: traefik
  tag: 1.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceindex:
  repository: pbortnik/rp5-index
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

uat:
  repository: pbortnik/rp5-uat
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  sessionLiveTime: 86400

serviceui:
  repository: pbortnik/rp5-ui
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

serviceapi:
  repository: pbortnik/rp5-api
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 300m
      memory: 1500Mi

migrations:
  repository: pbortnik/rp5-migrations
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi


postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    address: db-postgresql.default.svc.cluster.local
    port: 5432
    user: postgres
    dbName: reportportal

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint: 
    external: true
    address: mq-rabbitmq-ha.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq

# ingress configuration for the ui
ingress:
  hosts:
    - reportportal.k8.com

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true