apiVersion: v1
kind: Service
metadata:
  name: api-0
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8585
    protocol: TCP
    targetPort: 8585
  selector:
    component: reportportal-api
  type: ClusterIP
