apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      name: web
    - protocol: TCP
      port: 8081
      name: admin
  selector:
    component: reportportal-gateway
  type: NodePort
