apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrations
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-migrations
  template:
    metadata:
      labels:
        component: reportportal-migrations
    spec:
      containers:
      - env:
        - name: POSTGRES_SERVER
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.endpoint.dbName }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        image: "{{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
