apiVersion: v1
kind: Service
metadata:
  name: migrations-0
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: reportportal-migrations
  type: ClusterIP
