apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrations
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-migrations
  template:
    metadata:
      labels:
        component: reportportal-migrations
    spec:
      containers:
      - env:
        - name: RP_DB_HOST
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: RP_DB_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: RP_DB_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SeacretName }}"
              key: "postgresql-password"
        image: "{{ .Values.migrations.repository }}:{{ .Values.migrations.tag }}"
        name: migrations
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
