apiVersion: v1
kind: Service
metadata:
  name: uat-0
  labels: {{ include "labels" . | indent 4 }}
spec:
  ports:
  - name: headless
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    component: reportportal-uat
  type: ClusterIP
