apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-uat
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - env:
        - name: RP_SESSION_LIVE
          value: "3600"
        - name: RP_DB_HOST
          value: "{{ .Values.postgresql.endpoint.address }}"
        - name: RP_DB_PORT
          value: "{{ .Values.postgresql.endpoint.port }}"
        - name: RP_DB_USER
          value: "{{ .Values.postgresql.endpoint.user }}"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.postgresql.SecretName }}"
              key: "postgresql-password"
        name: uat
        image: "{{ .Values.uat.repository }}:{{ .Values.uat.tag }}"
        ports:
        - containerPort: 9999
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.uat.resources.requests.cpu }}
            memory: {{ .Values.uat.resources.requests.memory }}
          limits:
            cpu: {{ .Values.uat.resources.limits.cpu }}
            memory: {{ .Values.uat.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
